In [13]:
#final project
from sklearn.svm import SVR
from sklearn.metrics import r2_score
from sklearn.svm import SVC
from sklearn import svm
from sklearn.decomposition import PCA

from sklearn. decomposition import PCA as RandomizedPCA
from sklearn.preprocessing import StandardScaler, MinMaxScaler 

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import mean_squared_error 
import matplotlib.pyplot as plt

from sklearn import metrics

import warnings 
warnings.filterwarnings('ignore')


import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns; sns.set()
from sklearn import metrics

from sklearn.model_selection import train_test_split

In [14]:
df = pd.read_csv('https://raw.githubusercontent.com/Onkar-Indurkar/Intro-to-ML/main/forestfires.csv')
df.head()

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [15]:
list1 = ['month']

def binary_map (v1) :
    return v1.map({'jan' : 0, "feb": 1, "mar":2, "apr":3, "may":4, "jun":5, "jul":6, 'aug' : 7, "sep": 8, "oct":9, 'nov' : 10, "dec": 11})

df[list1] = df[list1] . apply(binary_map)
list2 = ['day']

def binary_map (v2) :
    return v2.map({'mon' : 0, "tue": 1, 'wed' : 2, "thu": 3, 'fri' : 4, "sat": 5, 'sun' : 6 })

df[list2] = df[list2] . apply(binary_map)
df.tail()

X  Y  month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
512  4  3      7    6  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44
513  2  4      7    6  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29
514  7  4      7    6  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16
515  1  4      7    5  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00
516  6  3     10    1  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00

In [63]:
x = df.iloc[:, [4,5,6,7,8,9,10]].values #1st 12 cols
y = df.iloc[:, 12].values   #13th col 


y[y >0 ] = 1
y = y.astype(int)
y = y.reshape(-1,1)

In [64]:
from sklearn import preprocessing
from sklearn import utils

lab_enc = preprocessing.LabelEncoder()
encoded = lab_enc.fit_transform(y)

In [65]:
#spliting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, train_size=0.8, test_size=0.2, random_state = 0)

In [66]:
#scaling/standardizing the dataset
from sklearn.preprocessing import StandardScaler 
sc_X = StandardScaler()

X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [67]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# List of kernel names and C values to try
kernel_list = ['linear', 'poly', 'rbf', 'sigmoid']
C_list = [0.1, 1, 10, 100]

# Iterate over kernel names and C values
for kernel in kernel_list:
    for C in C_list:
        print("Kernel:", kernel)
        print("C:", C)
        
        # Create classifier with current kernel and C value
        classifier = SVC(kernel=kernel, C=C)
        
        # Train classifier and make predictions
        classifier.fit(X_train, Y_train)
        Y_pred = classifier.predict(X_test)
        
        # Evaluate performance
        cnf_matrix = confusion_matrix(Y_test, Y_pred)
        accuracy_rate = accuracy_score(Y_test, Y_pred)
        precision_rate = precision_score(Y_test, Y_pred)
        recall_rate = recall_score(Y_test, Y_pred)
        
        # Print evaluation results
        print("Confusion Matrix:")
        print(cnf_matrix)
        print("Accuracy:", accuracy_rate)
        print("Precision:", precision_rate)
        print("Recall:", recall_rate)
        print("")


Kernel: linear
C: 0.1
Confusion Matrix:
[[14 30]
 [ 4 56]]
Accuracy: 0.6730769230769231
Precision: 0.6511627906976745
Recall: 0.9333333333333333

Kernel: linear
C: 1
Confusion Matrix:
[[16 28]
 [15 45]]
Accuracy: 0.5865384615384616
Precision: 0.6164383561643836
Recall: 0.75

Kernel: linear
C: 10
Confusion Matrix:
[[16 28]
 [15 45]]
Accuracy: 0.5865384615384616
Precision: 0.6164383561643836
Recall: 0.75

Kernel: linear
C: 100
Confusion Matrix:
[[16 28]
 [15 45]]
Accuracy: 0.5865384615384616
Precision: 0.6164383561643836
Recall: 0.75

Kernel: poly
C: 0.1
Confusion Matrix:
[[ 9 35]
 [ 1 59]]
Accuracy: 0.6538461538461539
Precision: 0.6276595744680851
Recall: 0.9833333333333333

Kernel: poly
C: 1
Confusion Matrix:
[[10 34]
 [ 8 52]]
Accuracy: 0.5961538461538461
Precision: 0.6046511627906976
Recall: 0.8666666666666667

Kernel: poly
C: 10
Confusion Matrix:
[[12 32]
 [16 44]]
Accuracy: 0.5384615384615384
Precision: 0.5789473684210527
Recall: 0.7333333333333333

Kernel: poly
C: 100
Confusion Ma

In [9]:
# from sklearn.decomposition import PCA

# accuracy_rate1 = [] 
# precision_rate1 = [] 
# recall_rate1 = []

# for k in range(1, 8):
#     print("Number of PCA components:", k)
    
#     pca = PCA(n_components=k)
#     principalComponents = pca.fit_transform(x)
#     principalDf = pd.DataFrame(data = principalComponents)
    
#     from sklearn.model_selection import train_test_split
#     X_train, X_test, Y_train, Y_test = train_test_split(principalComponents, y, train_size=0.8, test_size=0.2, random_state=60) 

#     kernel_list = ['linear', 'poly', 'rbf', 'sigmoid']
#     C_list = [0.1, 1, 10, 100]

#     # Iterate over kernel names and C values
#     for kernel in kernel_list:
#         for C in C_list:
#             print("Kernel:", kernel)
#             print("C:", C)

#             # Create classifier with current kernel and C value
#             classifier = SVC(kernel=kernel, C=C)

#             # Train classifier and make predictions
#             classifier.fit(X_train, Y_train)
#             Y_pred = classifier.predict(X_test)

#             # Evaluate performance
#             cnf_matrix = confusion_matrix(Y_test, Y_pred)
#             accuracy_rate = accuracy_score(Y_test, Y_pred)
#             precision_rate = precision_score(Y_test, Y_pred)
#             recall_rate = recall_score(Y_test, Y_pred)

#             # Print evaluation results
#             print("Confusion Matrix:")
#             print(cnf_matrix)
#             print("Accuracy:", accuracy_rate)
#             print("Precision:", precision_rate)
#             print("Recall:", recall_rate)
#             print("")

In [12]:
# from sklearn.svm import SVC
# from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score
# from sklearn.model_selection import KFold

# # List of kernel names and C values to try
# kernel_list = ['linear', 'poly', 'rbf', 'sigmoid']
# C_list = [0.1, 1, 10, 100]

# # Initialize variables for best performance
# best_accuracy = 0
# best_precision = 0
# best_recall = 0
# best_kernel = ""
# best_C = 0

# # Perform k-fold cross validation for k=5 and k=10
# for k in [5, 10]:
#     kf = KFold(n_splits=k, shuffle=True, random_state=0)
    
#     print(f"k-Fold Cross Validation (k={k})")
    
#     # Iterate over kernel names and C values
#     for kernel in kernel_list:
#         for C in C_list:
#             print("Kernel:", kernel)
#             print("C:", C)

#             # Initialize variables for current performance
#             current_accuracy = 0
#             current_precision = 0
#             current_recall = 0
            
#             # Train and evaluate classifier for each fold
#             for train_index, test_index in kf.split(X_train):
#                 # Split data into training and validation sets for current fold
#                 X_fold_train, X_fold_val = X_train[train_index], X_train[test_index]
#                 Y_fold_train, Y_fold_val = Y_train[train_index], Y_train[test_index]

#                 # Create classifier with current kernel and C value
#                 classifier = SVC(kernel=kernel, C=C)

#                 # Train classifier and make predictions on validation set
#                 classifier.fit(X_fold_train, Y_fold_train)
#                 Y_pred = classifier.predict(X_fold_val)

#                 # Evaluate performance on validation set
#                 current_accuracy += accuracy_score(Y_fold_val, Y_pred)
#                 current_precision += precision_score(Y_fold_val, Y_pred)
#                 current_recall += recall_score(Y_fold_val, Y_pred)

#             # Calculate average performance across all folds
#             current_accuracy /= k
#             current_precision /= k
#             current_recall /= k

#             # Print evaluation results for current kernel and C value
#             print("Accuracy:", current_accuracy)
#             print("Precision:", current_precision)
#             print("Recall:", current_recall)
#             print("")

#             # Update best performance variables if current performance is better
#             if current_accuracy > best_accuracy:
#                 best_accuracy = current_accuracy
#                 best_precision = current_precision
#                 best_recall = current_recall
#                 best_kernel = kernel
#                 best_C = C

# # Print best performance and corresponding kernel and C values
# print("Best Accuracy:", best_accuracy)
# print("Best Precision:", best_precision)
# print("Best Recall:", best_recall)
# print("Best Kernel:", best_kernel)
# print("Best C:", best_C)
